### PR TITLE
option show all way description / title only if truncated 

### PR DESCRIPTION
**Pull request by melomane63**
It is redundant to show title if it is not truncated, and we have options for this.
but this stop to show  description of application. 

My request is the optional possibility to 
all way show description 
and
show title only if it is truncated

### CODE REVIEW

**Comment by karlitos** [comment]
Hello Raphael, many thanks to your PR, I will merge them after I resolve the merge conflicts, although I was not touching this extension for some time and currently I am not event using Gnome Shell on a daily basis. I will update the Readme linking to your Repository, since you do the most current development and are way ahead of myself. Keep up the good work! As a small contribution from my side I will add some Czech localization ASAP

**Comment by karlitos** [comment]
May I ask you for a favor ? Would you be interested to look at this minimal extension I forked some years ago: https://github.com/karlitos/AppsOnTop
I never got into the process of publishing extensions, the original repository is dismissed and it may still be useful for other users. Sorry for spamming this PR, but I couldn't find a better way to contact you.

**Comment by RaphaelRochet** [comment]
@melomane63 please open an issue on https://github.com/RaphaelRochet/applications-overview-tooltip/issues 
@karlitos please deny this PR, will be a pain to merge (and useless I guess)
For AppsOnTop, is there a link with https://extensions.gnome.org/extension/472/apps-on-top/ ? I don't see many people asking for it though ..

**Comment by karlitos** [comment]
I will merge anyway since my repository was way ahead of yours. I will mention it in the Readme.

Not many people are asking for AppsOnTop since it stayed unmaintained for very long time ans only users with very old gnome-shell version were able to use it. But I never forget the intentions of the gnome-shell authors putting the Apps-button on the bottom of the screen forcing the users to always move the mouse cursor the whole "dock height" to open the apps overview. Maybe this extension would raise more attention if it will be usable in the current gnome versions.

**Comment by RaphaelRochet** [comment]
Okay I'll check it out. I must admit this apps button on top is a good idea. And it seems ti be a real simple hack !
BTW, do you have something to reply about this license question : https://github.com/RaphaelRochet/applications-overview-tooltip/issues/7 ?

**Pull request merged**
